"""Full data backup as a ZIP (Mongo export adapted from the SQLite spec)."""
import io
import json
import zipfile
from datetime import datetime

from db import db, programs_col, sessions_col
from audit import audit_csv_bytes
from logic import attendance_records_col, sow_records_col

users_col = db["users"]


def _ordinal(n):
    if 10 <= n % 100 <= 20:
        return "th"
    return {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")


async def _all(col, exclude_sensitive=False):
    proj = {"_id": 0}
    if exclude_sensitive:
        proj["password_hash"] = 0
    out = []
    async for d in col.find({}, proj):
        out.append(d)
    return out


async def build_backup(admin_name):
    now = datetime.now()
    programs = await _all(programs_col)
    sessions = await _all(sessions_col)
    attendance = await _all(attendance_records_col)
    sow_records = await _all(sow_records_col)
    users = await _all(users_col, exclude_sensitive=True)
    audit_bytes = await audit_csv_bytes()

    # Full Mongo export (adapted from "database.sqlite")
    database_dump = {
        "programs": programs,
        "sessions": sessions,
        "attendance_records": attendance,
        "sow_records": sow_records,
        "users": users,
    }

    programs_json = json.dumps(
        [{**p, "sessions": [s for s in sessions if s["program_id"] == p["id"]]} for p in programs],
        indent=2, default=str)

    info = (
        f"EdTech Ops Hub — Full Backup\n"
        f"Date of backup : {now.strftime('%d %b %Y, %H:%M:%S')}\n"
        f"Total programs : {len(programs)}\n"
        f"Total sessions : {len(sessions)}\n"
        f"Total users    : {len(users)}\n"
        f"Generated by   : {admin_name}\n"
    )

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("database.json", json.dumps(database_dump, indent=2, default=str))
        z.writestr("programs.json", programs_json)
        z.writestr("attendance_records.json", json.dumps(attendance, indent=2, default=str))
        z.writestr("audit_log.csv", audit_bytes)
        z.writestr("sow_records.json", json.dumps(sow_records, indent=2, default=str))
        z.writestr("backup_info.txt", info)
    buf.seek(0)

    fname = f"EdTechOpsHub_Backup_{now.day}{_ordinal(now.day)}{now.strftime('%b%Y')}.zip"
    meta = {
        "filename": fname,
        "created_at": now.isoformat(),
        "total_programs": len(programs),
        "total_sessions": len(sessions),
        "total_users": len(users),
        "generated_by": admin_name,
    }
    return buf.getvalue(), fname, meta
